services:
  db:
    image: postgres:16
    container_name: stock_postgres
    environment:
      POSTGRES_DB: stock_control
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_user -d stock_control"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: